baseURL = 'https://arjnep.github.io/less/'
languageCode = 'en-us'
title = 'Less'

[module]
  [[module.imports]]
    path = 'github.com/arjnep/less'

paginate = 3

[params]
    author = true
    authorName = 'arjnep'
    authorLink = 'https://github.com/arjnep'
    archive = true
    tags = true

[social]
    github = 'https://github.com/arjnep/less'
    rss = 'https://arjnep.github.io/less/index.xml'

[taxonomies]
  tag = 'tags'

[markup]
  [markup.highlight]
    style = 'dracula'


